### ISSUE TITLE
Feature Request: Parameter to not delete already verified parameters

### ISSUE THREAD

**Issue by pmersch2** [seeebiii/ses-verify-identities#506]
Checked only for Emails. Guessing it is the same for Domains.

What I did

- added manually mail "sample1@xyz.com" -> verified
- added manually mail "sample2@xyz.com" -> not verified
- included in cdk "sample1@xyz.com" + "sample2@xyz.com" + "sample3@xyz.com"

What happened:
- "sample1@xyz.com" **remained** while cdk deploy, but **deleted on cdk destroy**
- "sample2@xyz.com" **remained** while cdk deploy, but **deleted on cdk destroy**
- "sample3@xyz.com" **added** while cdk deploy, but **deleted on cdk destroy**

Every time i delete the stack all email addresses will be deleted as well as long as they are mentioned in the file. 

- no matter if verified or not
- Even though the stack did not create them (been in place before but could theoretically being added by the stack).

I would love some optional parameter to determine if already verified Emails should be removed as well like (deleteVerified?: boolean).

Reasoning: once a mail got deleted, it needs to be verified again once it is added back. Imagine you would have dozens of emails here and need to verify them all over again :)

**Comment by seeebiii** [comment]
Hi @pmersch2 , thanks for your suggestion and sorry for my late reply! I totally understand the requirement and I think it'd be a useful addition. I'll look into it soonish.

**Comment by pflorek** [comment]
@seeebiii that PR makes the construct to retain the email by default. IDK if should be a breaking change...

**Comment by seeebiii** [comment]
@pflorek I have already merged it but thinking about it again, this was probably a breaking change since the default is now that the resources are retained whereas before this change the resources were deleted. I still agree that it definitely makes sense to keep the resources in this case and do not automatically delete them but it's a different behavior. I'll revert it again and make the default as `DESTROY` since this was the behavior before.
